## Python básico 06/04

In [1]:
print("hello")

hello


## Variables en python

### Simples

-str
-bool
-float
-int

### Compuestos

- list: mutable []
- tupla: inmutable, no se modifica ()
- set: conjunto valores únicos {}
- diccionario: clave-valor {key : value}


In [20]:
#ejercicios
a= 10
print(a)

b=10.0
print(b)

c= """
hola"""
print(c)

d= c*a
print(d)

e= True
(e and e)
(e and not e)

l = ["a","b",1,True] #mixed type list
l.append("hola")
l.pop(1) #pop es pa quitar,se elimina el b

#listas por comprensión
comp_list = [i for i in range(10) if i%2==0] #esto es una lista por comprensión, se crea una lista con los números del 0 al 9 que sean pares
print(comp_list)

#tuplas
t= (1,2,3) #las tuplas son inmutables, no se pueden modificar

#diccionarios
d = {"eduardo": {"edad": 26, "ciudad": "Madrid"}, "diego": {"edad": 30, "ciudad": "Barcelona"}}#los diccionarios son mutables, se pueden modificar
print(d["eduardo"]["edad"])
print(d["diego"]["edad"])

10
10.0

hola

hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
[0, 2, 4, 6, 8]
26
30


## Condicionales

In [14]:
if d["eduardo"]["edad"] > 18:
    print("Eduardo es mayor de edad")
elif d["eduardo"]["edad"]< 0:
    print("Eduardo no ha nacido")
else:    print("Eduardo es menor de edad")

Eduardo es mayor de edad


## Excepciones : controlar muchas variables

In [15]:
try:  #intentar hacer algo, si no se puede, ir al except
    print(d["eduardo"]["altura"]) #esto va a dar error porque no existe la clave "nombre" en el diccionario de eduardo
except Exception as e: #capturar el error y guardarlo en la variable e
    print("Error:", e) #imprimir el error

Error: 'altura'


## Bucles

- for
- while 

In [17]:
for a in d.keys(): #iterar sobre las claves del diccionario
    print("el estudiante",a,"tiene",d[a]["edad"],"años") #imprimir la edad de cada persona en el diccionario

el estudiante eduardo tiene 25 años
el estudiante diego tiene 30 años


## Listas por compresión

In [21]:
comp_list =[a for a in d.keys() 
            if d[a]["edad"] > 25 and 
            d[a]["ciudad"] == "Madrid"] #esto es una lista por comprensión, se crea una lista con las claves del diccionario
print(comp_list)

['eduardo']


## Numpy

Manipula matrices y tensores (matriz n dimensional)

In [22]:
import numpy as np 


In [24]:
scalar = np.array([-1.5])
scalar

array([-1.5])

In [29]:
#array inmuable, no se pueden modificar sus elementos
#lista mutable, se pueden modificar sus elementos, no es fijo
array = np.array([1,2,2.6,3,4])
array.dtype #tipo de datos del array


dtype('float64')

In [31]:
array = np.array([1,2,"hola",3,4])
array.dtype #tipo de datos del array


array2= np.array([5,6,7,8,9])
array3= np.concat([array,array2]) #concatenar dos arrays
array3

array(['1', '2', 'hola', '3', '4', '5', '6', '7', '8', '9'], dtype='<U21')

## Número aleatorios

In [39]:
#si lo ejecuto varias veces, me va a dar un número diferente cada vez, porque es aleatorio
np.random.rand(1,10)

array([[0.47496477, 0.83630396, 0.21036604, 0.97064015, 0.03841948,
        0.91582258, 0.72826723, 0.84561221, 0.43413926, 0.7975359 ]])

In [42]:
#pa fijar el número aleatorio, para que siempre me de el mismo resultado, se usa la función seed
np.random.seed(42)
np.random.rand(1,10)

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
        0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258]])

In [43]:
random_array = np.random.rand(1,10) #crear un array de 1x10 con números aleatorios entre 0 y 1
random_array

array([[0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497,
        0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914]])

In [48]:
my_array = random_array.reshape(5,2) #cambiar la forma del array a 5x2 FILAS, COLUMNAS 
my_array

array([[0.02058449, 0.96990985],
       [0.83244264, 0.21233911],
       [0.18182497, 0.18340451],
       [0.30424224, 0.52475643],
       [0.43194502, 0.29122914]])

In [ ]:
#sacar la traspuesta de un array
my_array.T

array([[0.02058449, 0.83244264, 0.18182497, 0.30424224, 0.43194502],
       [0.96990985, 0.21233911, 0.18340451, 0.52475643, 0.29122914]])

In [50]:
unos = np.ones((2,5)) #crear un array de 2x5 con unos
unos

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [55]:
my_array2 = my_array.reshape(2,5) #deben estar ambas en la misma dimensión para poder sumarlas
unos * 2 + my_array2 #agregar ruido a mi array

my_array2.std() #desviación estándar
my_array2.std() ** 2 #varianza de mi array

np.float64(0.08228519299318053)

## Crear espacios lineales

In [56]:
np.linspace(0,10,5) #crear un array de 5 números equidistantes entre 0 y 10

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [57]:
np.arange(0,10,0.5) #crear un array de números del 0 al 10 con un paso de 0.5

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

## Resolver problemas de ecuaciones con matrices

In [59]:
A= np.random.rand(3,3) #crear un array de 3x3 con números aleatorios entre 0 y 1
A

array([[0.04645041, 0.60754485, 0.17052412],
       [0.06505159, 0.94888554, 0.96563203],
       [0.80839735, 0.30461377, 0.09767211]])

In [60]:
B = np.random.rand(3,1) #crear un array de 3x1 con números aleatorios entre 0 y 1
B

array([[0.68423303],
       [0.44015249],
       [0.12203823]])

In [61]:
np.linalg.solve(A,B) #resolver el sistema de ecuaciones Ax=B, donde A es la matriz de coeficientes, B es el vector de términos independientes y x es el vector de incógnitas

array([[-0.26754214],
       [ 1.39974953],
       [-0.90163283]])

## Pandas

In [62]:
import pandas as pd
